[package]
name = "kdlize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kdl = "^6"
thiserror = "^2.0"
anyhow = "^1.0"
miette = "^7.6"
