[package]
name = "kdlize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kdl = { version = "6", git = "https://github.com/kdl-org/kdl-rs" }
thiserror = "^2.0"
anyhow = "^1.0"
